create table role (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, email varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
create table role (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, email varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
create table role (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, email varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
create table role (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, email varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
create table role (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, email varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
create table role (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, email varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
